#1.连接数据库，并且配置，数据监控的信息，可以自己配置，也可以，使用官方的依赖，然后在配置文件中加上信息
#说白了下面的是，控制层和数据库层间的连接使者，可以管控两者的行为
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    # 01.监控页的配置
    druid:
      filters: stat,wall  #,web的监控和开始防火墙
      stat-view-servlet:
        enabled: true  #想要的功能默认开启
        login-password: 1 #登陆页面的密码
        login-username: a #登陆页面的用户名
        reset-enable: false  #重置功能关闭
      web-stat-filter:
        enabled: true
        url-pattern: /* #监控那些
        exclusions: '*.js,*.gif,*.jpg,*.css,*.ico,/druid/*' #表示排除那些地址
      aop-patterns: com.sias.boot.* #监控这个地址下面的包
  #02.把这个项目加入到监控服务器上
  boot:
    admin:
      client:
        url:  http://localhost:8888
        instance:
          prefer-ip: true
  application:
    name: SpringBoot3


  #02.阿里云的使用，注意一点的是，下面账户的名字，后面不可以使用数字，会导致连接不上      api-path:
#  redis:
#    host: r-bp10fp301i7jskko3epd.redis.rds.aliyuncs.com
#    port: 6379
#    password: myredis:HU3226ding328159@


#2.Mybatis配置文件地址
#  为什么呢，原因是底层要加载这些数据
mybatis-plus:
  #01.使用当前文件中的信息，但是，要么使用xml中的，要么使用yaml中的，不可以两个都加载
  #就是，要么config-location,要么configuration
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  #02.开始驼峰命名，可以在mybatis-config.xml配置，同时也可以在当前地址下配置
  #指定mybatis全局配置文件中的相关配置
  configuration:
    map-underscore-to-camel-case: true



#3.开启监控指标
management:
  endpoints:
    enabled-by-default: true  #默认开启所有的监控端点（以什么样子的方式开启，不知道）
    web:
      exposure:
        include: '*'    #web的方式开启
  #具体到详细的监控
  endpoint:
    health:
      show-details: always

#